sudo: required
services:
  - docker

before_install
  - build -t udagram-frontend ./udagram-frontend

after_success:
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push godinson/udagram-reverseproxy
  - docker push godinson/udagram-frontend
  - docker push godinson/udagram-api-feed
  - docker push godinson/udagram-api-user